---
sudo: required

services:
  - docker-compose

language: bash

before_install:
  - docker-compose version
  - sed -i.bu 's/user-name/'$(whoami)'/g' docker-compose.yaml
  - docker-compose pull
  - docker-compose build
  - docker-compose create
  - docker-compose start

script:
  - docker-compose ps

after_success:
  - docker-compose kill
